const addedComponentTest = {
  ancestors: [],
  appDir: '',
  components: [
    {
      actions: [],
      childrenArray: [],
      color: '#FF6D00',
      componentState: [],
      focusChildId: 0,
      id: 1,
      nextChildId: 1,
      nextPropId: 1,
      props: [],
      selectors: [],
      stateful: false,
      title: 'App',
    },
    {
      actions: [],
      childrenArray: [],
      color: '#b90061',
      componentState: [],
      focusChildId: 0,
      id: 2,
      nextChildId: 1,
      nextPropId: 1,
      props: [],
      selectors: [],
      stateful: false,
      title: 'Test',
    },
  ],
  errorOpen: false,
  focusChild: {
    HTMLInfo: null,
    childComponentId: 0,
    childId: 0,
    childSort: 0,
    childType: null,
    color: null,
    componentName: null,
    htmlElement: null,
  },
  focusComponent: {
    actions: [],
    childrenArray: [],
    color: '#b90061',
    componentState: [],
    focusChildId: 0,
    id: 2,
    nextChildId: 1,
    nextPropId: 1,
    props: [],
    selectors: [],
    stateful: false,
    title: 'Test',
  },
  initialApplicationFocusChild: {
    HTMLInfo: null,
    childComponentId: 0,
    childId: 0,
    childSort: 0,
    childType: null,
    color: null,
    componentName: null,
    htmlElement: null,
  },
  loading: false,
  nextId: 3,
  selectableChildren: [1],
  storeConfig: { interfaces: {}, reducers: {} },
  successOpen: false,
  totalComponents: 2,
};
